// Declare all the instruction related defines here
// funct3/funct7 field for all the supported instructions
`define ADD         6'h0
`define ADDI        6'h17
`define AND         6'h7
`define ANDI        6'h1c
`define BEQ         6'h0
`define BNE         6'h1
`define BLT         6'h4
`define BGE         6'h5
`define BLTU        6'h6
`define BGEU        6'h7
`define JAL         6'h3
`define JALR        6'h9
`define LB          6'h0
`define LBU         6'h4
`define LH          6'h1
`define LHU         6'h5
`define LW          6'h2
`define AUIPC       6'h27
`define LUI         6'h37
`define OR          6'h6
`define ORI         6'h16
`define SB          6'h0
`define SH          6'h1
`define SW          6'h2
`define SLL         6'h1
`define SLLI        6'h1
`define SLT         6'h2
`define SLTI        6'h12
`define SLTIU       6'h1b
`define SLTU        6'h3
`define SRA         6'hd
`define SRAI        6'h15
`define SRL         6'h5
`define SRLI        6'h5
`define SUB         6'h8
`define XOR         6'h4
`define XORI        6'h14

`define R_TYPE      7'h33
`define I_TYPE_0    7'h03
`define I_TYPE_1    7'h13
`define S_TYPE      7'h23
`define B_TYPE      7'h63
`define J_TYPE      7'h6F
